---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::default]
  - name: chef10
    run_list:
    - recipe[build-essential]
    - recipe[minitest-handler]
    - recipe[backup_test::default]
    provisioner:
      require_chef_omnibus: 10.30.2